[env:t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_deps =
  moononournation/GFX Library for Arduino @ ^1.5.3
  bblanchon/ArduinoJson @ ^7.0.4
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
